#!/usr/bin/env python3
"""Exact local checks for L015; the global geometric argument is in the lemma."""

from fractions import Fraction
import importlib.util
from pathlib import Path


def rank(rows):
    if not rows:
        return 0
    matrix = [[Fraction(x) for x in row] for row in rows]
    pivot = 0
    for column in range(len(matrix[0])):
        found = next((i for i in range(pivot, len(matrix))
                      if matrix[i][column]), None)
        if found is None:
            continue
        matrix[pivot], matrix[found] = matrix[found], matrix[pivot]
        factor = matrix[pivot][column]
        matrix[pivot] = [x / factor for x in matrix[pivot]]
        for i in range(len(matrix)):
            if i != pivot and matrix[i][column]:
                factor = matrix[i][column]
                matrix[i] = [x - factor * y
                             for x, y in zip(matrix[i], matrix[pivot])]
        pivot += 1
        if pivot == len(matrix):
            break
    return pivot


# Exponents are r,q,z. A fourth variable w just extends the coefficient ring.
ZERO = (0, 0, 0)
R, Q, Z = (1, 0, 0), (0, 1, 0), (0, 0, 1)
IDEAL = ((0, 0, 2), (0, 1, 1), (1, 2, 0))


def plus(a, b):
    return tuple(x + y for x, y in zip(a, b))


def divides(a, b):
    return all(x <= y for x, y in zip(a, b))


def standard(monomial):
    return not any(divides(g, monomial) for g in IDEAL)


def monomials(degree):
    return [(r, q, degree - r - q)
            for r in range(degree + 1) for q in range(degree - r + 1)
            if standard((r, q, degree - r - q))]


def check_ideal_and_normal_module():
    # Intersection of monomial ideals is generated by pairwise least multiples.
    reduced = (Z, R)
    squared = ((0, 0, 2), (0, 1, 1), (0, 2, 0))
    candidates = {tuple(max(x, y) for x, y in zip(a, b))
                  for a in reduced for b in squared}
    minimal = {m for m in candidates
               if not any(n != m and divides(n, m) for n in candidates)}
    assert minimal == set(IDEAL)

    # Independently form the linear equations for Hom(I,R/I) in each shift.
    # q*F-z*G=0 and rq*G-z*H=0 have output degrees shift+3, shift+4.
    for shift in range(-3, 7):
        degrees = (shift + 2, shift + 2, shift + 3)
        columns = [(component, m) for component, degree in enumerate(degrees)
                   for m in monomials(degree)]
        indices = {column: i for i, column in enumerate(columns)}
        constraints = {}
        actions = {0: ((0, Q, 1),),
                   1: ((0, Z, -1), (1, plus(R, Q), 1)),
                   2: ((1, Z, -1),)}
        for column, (component, m) in enumerate(columns):
            for relation, multiplier, sign in actions[component]:
                product = plus(m, multiplier)
                if standard(product):
                    row = constraints.setdefault(
                        (relation, product), [0] * len(columns))
                    row[column] += sign
        rows = list(constraints.values())
        kernel_dimension = len(columns) - rank(rows)

        # Formula (6) produces independent monomial vectors in this kernel.
        predicted = []
        for component, degree in enumerate(degrees):
            possible = []
            if component == 0:
                if degree >= 2:
                    possible.append((degree - 1, 1, 0))  # rq*A(r)
                if degree >= 1:
                    possible.append((degree - 1, 0, 1))  # z*B(r)
            else:
                if degree >= 1:
                    possible += [(degree - 1, 1, 0),
                                 (degree - 1, 0, 1)]
                if degree >= 2:
                    possible.append((0, degree, 0))
            for m in possible:
                vector = [0] * len(columns)
                vector[indices[(component, m)]] = 1
                assert all(sum(a * b for a, b in zip(row, vector)) == 0
                           for row in rows)
                predicted.append(vector)
        assert rank(predicted) == kernel_dimension
        expected = 0 if shift == -3 else 2 if shift == -2 else 6 if shift == -1 else 8
        assert kernel_dimension == expected, (shift, kernel_dimension)

    # Generic ordinary square in two normal variables has basis 1,q,z.
    assert sum(1 for q in range(3) for z in range(3) if q + z < 2) == 3


# Dual-number matrices verify associativity and trace without symbolic packages.
def dual_add(a, b):
    return a[0] + b[0], a[1] + b[1]


def dual_multiply(a, b):
    return a[0] * b[0], a[0] * b[1] + a[1] * b[0]


def matrix_multiply(a, b):
    return [[(sum(a[i][k][0] * b[k][j][0] for k in range(3)),
              sum(a[i][k][0] * b[k][j][1] +
                  a[i][k][1] * b[k][j][0] for k in range(3)))
             for j in range(3)] for i in range(3)]


def multiplication_matrices(coefficients):
    a0, a1, a2, b0, b1, b2, c0, c1, c2 = coefficients
    x = [[(0, 0), (0, a0), (0, b0)],
         [(1, 0), (0, a1), (0, b1)],
         [(0, 0), (0, a2), (0, b2)]]
    y = [[(0, 0), (0, b0), (0, c0)],
         [(0, 0), (0, b1), (0, c1)],
         [(1, 0), (0, b2), (0, c2)]]
    return x, y


def trace(matrix):
    return (sum(matrix[i][i][0] for i in range(3)),
            sum(matrix[i][i][1] for i in range(3)))


def check_trace_section():
    columns = []
    for variable in range(9):
        coefficients = [0] * 9
        coefficients[variable] = 1
        x, y = multiplication_matrices(coefficients)
        xy, yx = matrix_multiply(x, y), matrix_multiply(y, x)
        columns.append([xy[i][j][1] - yx[i][j][1]
                        for i in range(3) for j in range(3)])
    constraints = [list(row) for row in zip(*columns)]
    assert rank(constraints) == 3
    assert {i for i, col in enumerate(columns) if any(col)} == {0, 3, 6}

    # Basis perturbations cover all six allowed coefficients. To first order
    # the displayed products and traces are linear in these coefficients.
    for variable in (1, 2, 4, 5, 7, 8):
        coefficients = [0] * 9
        coefficients[variable] = 1
        x, y = multiplication_matrices(coefficients)
        assert matrix_multiply(x, y) == matrix_multiply(y, x)
        assert trace(x) == (0, coefficients[1] + coefficients[5])
        assert trace(y) == (0, coefficients[4] + coefficients[8])
        for left, right in ((x, x), (x, y), (y, y)):
            assert trace(matrix_multiply(left, right)) == (0, 0)
            assert dual_multiply(trace(left), trace(right)) == (0, 0)

    # In (8), a1=M/r and b2=E: trace(q)/3 has residue M(0)/3.
    # The two j-identities have unknowns d,H_D*mu; their rank is two.
    assert rank([[1, 1], [1, Fraction(1, 3)]]) == 2
    # Mixed pairs 13 and 23 impose exactly two independent differences.
    differences = [[1, 0, -1], [0, 1, -1]]
    assert rank(differences) == 2
    assert rank(differences + [[1, -1, 0]]) == 2


def check_action_and_infinity():
    source = Path(__file__).resolve().parents[1] / "rm-cubic" / "check_correspondence.py"
    spec = importlib.util.spec_from_file_location("rm_cubic_arithmetic", source)
    arithmetic = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(arithmetic)
    theta = {j: {(0, 0, j): 1, (0, 0, 7 - j): 1} for j in (1, 2, 3)}
    add, scale = arithmetic.add, arithmetic.scale
    action = add(theta[1], scale(theta[2], 3), theta[3])
    formula = add(scale(arithmetic.power(theta[1], 2), 2),
                  scale(arithmetic.ONE, -5))
    assert arithmetic.cyclotomic_reduce(add(action, scale(formula, -1))) == {}
    for weights in ((6, 2), (3, 5), (6, 2)):
        for weight in weights:
            assert len({weight * k % 7 for k in (-3, -2, -1, 1, 2, 3)}) == 6


def main():
    check_ideal_and_normal_module()
    check_trace_section()
    check_action_and_infinity()
    print("PASS: mixed ordinary-square ideal and normal-module shifts -3 through 6.")
    print("PASS: rank-three associativity, multiplicative normalized trace, and residue incompatibility.")
    print("PASS: critical-pair constraint rank, nonuniform cycle action, and six infinity weights.")
    print("The fibrewise graph argument, recovery of C, and full family flatness require L015's proof.")


if __name__ == "__main__":
    main()
